// Code generated by "stringer -type=PinState"; DO NOT EDIT.

package io

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PinStateLow-0]
	_ = x[PinStateHigh-1]
}

const _PinState_name = "PinStateLowPinStateHigh"

var _PinState_index = [...]uint8{0, 11, 23}

func (i PinState) String() string {
	if i < 0 || i >= PinState(len(_PinState_index)-1) {
		return "PinState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PinState_name[_PinState_index[i]:_PinState_index[i+1]]
}
