// Code generated by 'yaegi extract github.com/denkhaus/sensor/types'. DO NOT EDIT.

package symbols

import (
	"github.com/denkhaus/sensor/types"
	"reflect"
)

func init() {
	Symbols["github.com/denkhaus/sensor/types/types"] = map[string]reflect.Value{
		// type definitions
		"ScriptContext": reflect.ValueOf((*types.ScriptContext)(nil)),
	}
}
