// Code generated by 'yaegi extract github.com/denkhaus/containers'. DO NOT EDIT.

package symbols

import (
	"reflect"
)

func init() {
	Symbols["github.com/denkhaus/containers/containers"] = map[string]reflect.Value{}
}
